### ISSUE TITLE
[Feature Request] Add an override for unsupported ROM size.

### ISSUE THREAD

**Issue by ObscenityIB** [Rodrigodd/gameroy#12]
I have a bootleg ROM dump that is _technically_ broken from being offset from the logo bypass it uses, I would like to load it in a debugger and came across this one.

However, I get the following error:

```
failed to load rom: Rom size '0d' is no supported
```

If it's possible, it would be great to have an override flag to force-load the ROM and view the assembly.

Depending on how this debugger operates, it may require padding out the ROM to the size it can handle.

**Comment by Rodrigodd** [comment]
The error you’re seeing happens because the cartridge header specifies an invalid ROM size. I could maybe turn this error into a warning and then infer the ROM size from the file size or something.

That said, since this is the first check GameRoy does when loading a ROM, and I don’t know how broken your ROM is, it might make more sense to add a way to override the detection. The info from the cartridge header is used to figure out which Multi-card chip the cartridge uses, so an override would need to specify the MBC type, the ROM size, and the RAM size.

When you say it’s "offset from the logo bypass it uses," do you mean the entire ROM dump is shifted? That would cause problems with bank switching.

I’ll take a look at this sometime next week. In the meantime, you could try patching your ROM with a hex editor to give it a valid header and pad it to an appropriate size, but just a suggestion.

**Comment by ObscenityIB** [comment]
Yes the entire dump is shifted, it's an MBC1 mapper type by Sachen, the ROM size is 524288 bytes.

For the RAM I would have to guess, it's not printed in the dump logs.

**Comment by Rodrigodd** [comment]
> Yes the entire dump is shifted

You will need to externally fix at least that before trying to load it in an emulator. I'm not sure how much of your ROM is missing, but it is probably missing the interrupt handlers, so it likely won't run for very long before derailing. It will probably fail to render the first frame.

For it to even start running in an emulator, you need to ensure the entry point is correct. It should be at byte index 256 (0x100) and generally contain a jump instruction to address 0x150, past the cartridge header.

**Comment by Rodrigodd** [comment]
Implement the support for overriding the MBC type, Rom size and Ram size. You need to open the rom using the command line:

```
./gameroy path/to/rom.gb --mbc=MBC1,0x80000,0x80000
```

You can also pass `-d` to make the emulator stop on the entry point. To test, you can use the artifacts from the last successful [Actions](https://github.com/Rodrigodd/gameroy/actions) run, or build gameroy from source.
